### ISSUE TITLE
Bug(s) 🐛 🐞 🐜

### ISSUE THREAD

**Issue by gracebilliris** [SIS-Team-24/2023-SIS-Team-24#170]
![Image](https://github.com/SIS-Team-24/2023-SIS-Team-24/assets/10949109/fccb2039-c992-4bfe-8216-7678bed756e8)

- [ ] Clear _input button_ function for the _text to be summarised_

**Comment by henrygoodman** [comment]
#190 may semi-solve the issue of the font being permanent (instead of being state in a React component that is reset upon reload)

This is achieved by encoding the state into the URL, so that if the page is reloaded, the font will stay selected. The only thing to consider is that if the user opens a brand new tab with no state encoded in URL, the font will be reset back to normal (so this use case may warrant setting in local Storage)
